### ISSUE TITLE
Unstable hash for different data input order

### ISSUE THREAD

**Issue by Pedrexus** [omry/omegaconf#1049]
**Describe the bug**
The hash of a DictConfig is not stable. `hash(cfg)` changes although python dict comparison returns true.

The problem for me is that when reading from a yaml file, different runs of the same script produce different hashes.

**To Reproduce**

```python
from omegaconf import DictConfig

d1 = DictConfig({"a": 1, "b": 2})
d2 = DictConfig({"b": 2, "a": 1})

d1 == d2, hash(d1) == hash(d2)
# (True, False)
```

It seems, the hash magic method is defined in a way that is not stable for different dictionary input orders:

```python
def __hash__(self) -> int:
    return hash(str(self))
```

**Expected behavior**
I think hash should be the same if dict data is the same, regardless of input order. 

Not sure actually if this behavior is expected by the project authors, but it was unexpected to me.

**Additional context**
The solution I'm using now is:

```
from omegaconf import OmegaConf
import hashlib
import json

d1 = DictConfig({"a": 1, "b": 2})
d1_hash = hashlib.sha1(json.dumps(OmegaConf.to_container(d1), sort_keys=True).encode()).hexdigest()
```

**Comment by Jasha10** [comment]
I believe this is because the order of the keys in the DictConfig makes a difference.
Under the hood, the DictConfig hash function [looks like this](https://github.com/omry/omegaconf/blob/d02a0c10cbba8b01c92e1faffa995ebf2da4abe2/omegaconf/dictconfig.py#L616):
```python
    def __hash__(self) -> int:
        return hash(str(self))
```
Thus the DictConfig hash's you gave differ for the same reason that the hashes of stringified standard python dicts would differ:
```python
>>> d1 = DictConfig({"a": 1, "b": 2})
>>> d2 = DictConfig({"b": 2, "a": 1})
>>> hash(str(d1)) == hash(str(d2))
False
```

**Comment by Jasha10** [comment]
> I think hash should be the same if dict data is the same, regardless of input order.

To push back on this, The order of keys in a python dict is part of the dict's api.
For example, calling `list({"a": 1, "b": 2}.items())` gives a different result from calling `list({"b": 2, "a": 1}.items())`. For this reason, I think it makes sense for the hash of objects to be different if the keys are different.

**Comment by Pedrexus** [comment]
I understand. Thanks for the reply. It's fine to leave it as a is, but I'd just point out that this [only seems to be stable for python>=3.7](https://mail.python.org/pipermail/python-dev/2017-December/151283.html), so in older python versions you could actually see the same object have different hashes upon a read event or such.

**Comment by Jasha10** [comment]
OmegaConf is soon dropping support for python3.6 anyway. (https://github.com/omry/omegaconf/issues/791).

**Comment by omry** [comment]
It seems correct that hash of equal DictConfigs is the same if the objects are considered equal by `==`.
This is very low pri because honestly, I am not sure what reason you have to hash those in the first place :).
I would not object to a pull request fixing it (maybe by using a variant of str that is sorting the keys from hash, or alternatively just make a proper faster implementation of hash).
