### ISSUE TITLE
improve exception message to contain full key when creatning a config with OmegaConf.create() that has an illegal value

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#14]
```
# TODO: improve exception message to contain full key a.b
def test_create_nested_dict_with_illegal_value():
```

**Comment by swist** [comment]
This is an interesting one, how do you see this happening? It seems like the default behaviours in `OmegaConf.create` is not helpful at making this work, from what I can tell all the other plumbing is there

**Comment by omry** [comment]
Look at the mentioned unit test function (test_create_nested_dict_with_illegal_value)

**Comment by swist** [comment]
Yep I had a poke at it. The problem is that when you call OmegaConf.create, `DictConfig` doesn't delegate to OmegaConf.create to set the parent correctly before setting the value, which means the nested-most example in the tree gets resolved and throws before any of the parents are set (because recursion).

**Comment by omry** [comment]
Yes. this is a tricky one.
I suspect it's possible to solve it by carefully changing of order of things during initialization.
