### ISSUE TITLE
[bug] ListConfig doesn't support negative indices in basic list operations

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#248]
```
from omegaconf import OmegaConf
a = OmegaConf.create({"a": [1, 2, 3, 4, 5, 6, 7, 8]})
b = [1, 2, 3, 4, 5, 6, 7, 8]
print(b[1:-1]) # Works fine
print(a.a[1:-1]) # Throws error
print(b[None:None:-1]) # Works fine
print(a.a[None:None:-1])  # Throws error
```

**Comment by omry** [comment]
This is a limitation of islice that is here to stay: https://bugs.python.org/issue33040
The alternative is to have a built in implementation inside ListConfig.__getitem__, but that's quiet a lot of work for marginal gain.
I am still open to a fix from you here, but this is not likely to happen otherwise.

I am planning to close this ticket in 6 months if no one provides a fix.

**Comment by pereman2** [comment]
Hi, I'd like to work on this. I'm trying to make my first contribution on github if you don't mind.

**Comment by omry** [comment]
@pereman2, that would be great!
keep in mind that the testing bar will be high for this one because it will be replacing a existing well tested implementation with a brand new one.

**Comment by omry** [comment]
@pereman2, one idea I just had:
you might still be able to use islice but just correct it's inputs from negative indices to positive ones.
If this covers everything we need it should be a straight forward fix.

**Comment by pereman2** [comment]
@omry, Cool I'll get to it !
In addition, the more_itertools library adds support for negative numbers( I don't know if that might be a bad practice).

**Comment by omry** [comment]
Awesome.
more_itertools seems nice, but I would like to keep OmegaConf only critical dependencies. it is a very low level project.
Let's stay clear of introducing new dependencies unless it's really worth it.
