### ISSUE TITLE
Support object style access of dictionary elements that include hyphen 

### ISSUE THREAD

**Issue by fjp** [omry/omegaconf#353]
Thanks for creating omegaconf, it's great. However, would it be possible to add object style access of dictionary elements that include hyphens? If for example a config includes `batch-size: 32` it's only possible to access it with `cfg["batch-size"]`. I'd like to access it using `cfg.batch_size`.  

Take for example [`Box`](https://github.com/cdgriffith/Box) which converts `batch-size` to `batch_size`. Therefore, it's possible to use `cfg.batch_size`. I think it would be awesome if this feature could be added to omegaconf.

**Comment by omry** [comment]
Thanks for the feature request @fjp.
Because OmegaConf also enables attribute style access as you pointed out, this would be a breaking change.

For example, this config would become illegal, or at least broken:
```yaml
cfg:
  batch-size: 10
  batch_size: 20
```

I will keep this open as a wishlist item to gauge interest and consider it if there is enough interest.

**Comment by omry** [comment]
Hi @fjp,
Given the lack of interest from the community I am closing this for now.
I think adding it is not worth the corner case issues it might introduce (such as the one I pointed out).
