### ISSUE TITLE
merging structured configs that contain dicts = crash

### ISSUE THREAD

**Issue by alexeib** [omry/omegaconf#441]
```python
>>> from omegaconf import DictConfig, OmegaConf
>>> a = OmegaConf.create({'d': {}})
>>> b = OmegaConf.create({'d': {'f': 3}})
>>> OmegaConf.merge(a,b)
{'d': {'f': 3}}
>>> OmegaConf.set_struct(a, True)
>>> OmegaConf.merge(a,b)
omegaconf.errors.ConfigKeyError: Key 'f' is not in struct
	full_key: d.f
	reference_type=Any
	object_type=dict
```

on the surface it is kind of behaving as one might expect, except that if you define a dataclass that contains a Dict[str, Any] type and then try to merge into it, you would expects dicts to get merged, but they are not

**Comment by omry** [comment]
Can you create an example that reproduces the problem you are reporting? (with a config that is created from a dataclass).
As you point out, your example should fail.

**Comment by omry** [comment]
```python
from omegaconf import OmegaConf, MISSING
from dataclasses import dataclass
from typing import *

@dataclass
class Foo:
    d : Dict[str, Any] = MISSING

c1 = OmegaConf.structured(Foo)
# OmegaConf.set_struct(c1, True) # Don't do this.
print(OmegaConf.merge(c1, {"d": {"a": 10}}))
# python 1.py 
# {'d': {'a': 10}}
```

If you do not set c1 to struct mode it works fine. I don't think you should be doing it if your top level config is based on a dataclass.

**Comment by alexeib** [comment]
i fixed it in my code by doing open_dict(...) but it seems hacky - you should be able to merge values inside dicts. try setting d to {"b": 5} and then merging your {"d": {"a": 10}} into it. shouldnt you be able to merge new values into a Dict[str, Any]? otherwise why would you declare it as a dict

**Comment by omry** [comment]
Can you fix it by not setting struct mode in the first place?
Your config is already strongly typed if you use dataclasses.
Struct mode is recursive. this is by design.

**Comment by alexeib** [comment]
open_dict effectively removes the "struct" mode temporarily, right? so i did fix it this way.
i guess my point is, if i have a dataclass, then not being able to add new fields to it makes sense, but it also makes sense to be able to add new fields into a property that is declared as a dict. currently this is not the case :(

**Comment by omry** [comment]
As I demonstrated in my code snippet, it is the case if you are not setting your config intro struct mode (which is the default behavior).
Struct mode was added as a limited form of Structured Configs.
Since are using Structured Configs, I don't understand why you are setting your config to struct mode.
Those two things have different semantics.

**Comment by omry** [comment]
If this is within Hydra, than this could be a bug in Hydra.
If the primary config file is Structured, I don't think it makes a lot of sense to set the config to struct mode.

**Comment by omry** [comment]
You initially created an example that does not reproduce the problem.
I took a guess at what you are might be doing and shown what you should be doing instead. 
You did not acknowledge my suggestion though and I don't know if you didn't because you didn't read it, didn't understand it, or maybe it's not valid because my guess of what you are doing is wrong.

Please create an example that demonstrate what you are doing, I think me guessing is not productive.

**Comment by alexeib** [comment]
so the goal is to have a config such that i can have something like:

MyConfig:
   dict_field: Dict[str, int]

i want to not be able to add new fields to MyConfig, however i want to be able to populate dict_config with arbitrary pairs of <str, int>. is this possible?

**Comment by omry** [comment]
Yes, it is possible. I demonstrated it in my first code snippet.
Here is a different version that has Dict[str, int]:
```python
from omegaconf import OmegaConf, MISSING
from dataclasses import dataclass, field
from typing import *

@dataclass
class Foo:
    d : Dict[str, int] = field(default_factory=dict)

c1 = OmegaConf.structured(Foo)
print("Empty config", c1)
config_with_arbitrary_dict = {"d":  {"a": 10, "b": 20}}

merged = OmegaConf.merge(c1, config_with_arbitrary_dict)
print("Merged", merged)
```

Output:
```
f$ python 1.py 
Empty config {'d': {}}
Merged {'d': {'a': 10, 'b': 20}}
```

**Comment by alexeib** [comment]
oh i see. then i guess i am confused, i thought "set_struct" is equivalent to using "OmegaConf.structured(...)", but it is more like setting a "read only" flag on a config?

**Comment by omry** [comment]
The flags implementation is uniform and described in the docs:

### Configuration flags
OmegaConf support several configuration flags. Configuration flags can be set on any configuration node (Sequence or Mapping). if a configuration flag is not set it inherits the value from the parent of the node. The default value inherited from the root node is always false.

This means flags are recursively.
Initially I thought that the struct flag would indeed be enough to implement Structured configs, but it's not that simple exactly because Structured should not be recursive. So on merge (and on set) a node being Structured Config or not is checked explicitly, making it a second way to close a node to changes that is not recursive.

OmegaConf structured is a simple wrapper on top of OmegaConf.create(), the only difference is that it returns Any and not Union[DictConfig, ListConfig].
The motivation is to support something like this without a type checker error:
```
user: User = OmegaConf.create(User()) 
```

As for Hydra:
It is setting the struct mode on the top level config right now by by default (unless you pass strict=False to hydra.main()).
This may actually result in errors similar to what you are describing (I did not test it yet).
If that's the case, Hydra should probably not set struct mode on the root config node if is backed by a Structured Config.

**Comment by alexeib** [comment]
i found the actual reason, it was because i was setting this before merge:
`dc_instance.__dict__["_parent"] = cfg.__dict__["_parent"]`
and then `cfg = OmegaConf.merge(dc_instance, cfg)`

if i instead chnge it to this:
```
    merged_cfg = OmegaConf.merge(dc, cfg)
    merged_cfg.__dict__["_parent"] = cfg.__dict__["_parent"]
    OmegaConf.set_struct(merged_cfg, True)
```

it now works as expected
