### ISSUE TITLE
Support loading yaml with serialized objects

### ISSUE THREAD

**Issue by ppwwyyxx** [omry/omegaconf#456]
**Is your feature request related to a problem? Please describe.**
pyyaml has basic supports to serialize/deserialize objects, but `OmegaConf.load` does not:
```python
import yaml
from omegaconf import OmegaConf

class A():
    pass

cfg = OmegaConf.create({"a": A()}, flags={"allow_objects": True})
OmegaConf.save(cfg, "out.yaml")

# cfg = OmegaConf.load("out.yaml")  # fails
cfg = OmegaConf.create(yaml.load(open("out.yaml")), flags={"allow_objects": True})  # works
print(cfg)
```

**Describe the solution you'd like**
would be good to support it

**Additional context**
https://github.com/omry/omegaconf/issues/382#issuecomment-696455065

**Comment by omry** [comment]
Hi @ppwwyyxx.
allow_objects is an internal API for now and I would rather it not being exposed in more places.
Since it's off by default, the only way to do what you are asking for is to add an optional flag to load, like:
```
cfg = OmegaConf.load("out.yaml", allow_objects=True) 
```
Which is in conflict with it being an internal API.

One of the primary reasons OmegaConf does not support arbitrary objects is the to avoid the exposure to all sorts of issues coming from serializing arbitrary objects as an officially supported thing.
To give you a sense of this surface area: consider also serializing with pickle where there are nested objects, and serializing objects that are derived from Structured Configs that has nested arbitrary objects as well.

For now I suggest that first load with yaml and then create as you did in your example above.
