### ISSUE TITLE
Subclass check for structured config merge is too strict?

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#724]
**Describe the bug**
Unexpected results when merging a dataclass with a subdataclass: the `issubclass` check seems to be backwards.

**To Reproduce**
Suppose we have a dataclass `Conf` and a subclass `SubConf`:
```python
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class Conf:
    x: int = 123

cfg = OmegaConf.structured(Conf)

@dataclass
class SubConf(Conf):
    x: int = 456
    y: int = 789

sub = OmegaConf.structured(SubConf)
```

It should be possible to merge `cfg` and `sub` to create a `DictConfig` that equals `{"x": 123, "y": 789}`, but neither `OmegaConf.merge(sub, cfg)` nor `OmegaConf.merge(cfg, sub)` produces this result.
```python
# merged = OmegaConf.merge(sub, cfg)  # fails: ValidationError: Merge error: Conf is not a subclass of SubConf.

merged = OmegaConf.merge(cfg, sub)
assert merged == {"x": 123, "y": 789}, f"Got {merged=}"  # fails: AssertionError: Got merged={'x': 456, 'y': 789}
```

**Additional context**
- [x] OmegaConf version: 2.1.0.rc1
- [x] Python version: 3.9.4

This bug report comes out of discussion in #721.

**Comment by Jasha10** [comment]
Looking at `DictConfig._validate_merge`, the current behavior is to disallow merging `Config` into `SubConfig`: `OmegaConf.merge(SubConfig, Config)` raises a ValidationError.

I propose the following API change:
```python
# This succeeds currently, with merged object_type == SubConfig:
assert OmegaConf.merge(Config, SubConfig) == {"x": 456, "y": 789}

# This fails currently. Should succeed with merged object_type == SubConfig:
assert OmegaConf.merge(SubConfig, Config) == {"x": 123, "y": 789}

# raise error if Config and Config2 are both structured, and neither is a subclass of the other:
raises(ValidationError):
    OmegaConf.merge(Config, Config2)
```

@omry and @odelalleau, could you please let me know what you think?

**Comment by odelalleau** [comment]
I agree the current behavior can indeed be surprising, but I can see why the `issubclass` check works like that: we have a generic `Conf`, and a specialized `SubConf` may inherit from it to override some fields and define new ones. And the desired result of the merge is a `SubConf` that takes the default values from `Conf` for fields that are not overridden by `SubConf` (that's the first scenario).

I think the API you're proposing makes sense. It can be understood as "we merge the second config into the first one, and the resulting object type is the lowest class in the hierarchy". I still think that it should be possible to make the last scenario work (either with `open_dict()` or a special argument to `merge`), in order to resolve #721.

**Comment by odelalleau** [comment]
Sorry, after giving it more thoughts and reading everything more carefully, I edited my previous comment to correct some items.

The bottom line is that I think what you're suggesting is a valid approach for 2.1 (*but* I still think we might want to simplify the merge logic in the future to make it easier to understand).

**Comment by omry** [comment]
> Got merged={'x': 456, 'y': 789}

This seems perfect to me.

**Comment by omry** [comment]
The semantics of merge is that it's layering the config on the right on top of the config on the left.
Why do you want x to not be overwritten in your example above?
In the following:
```python
res = OmegaConf.merge(c1, c2, c3)
```
The expectation is that any value defined in c3 will overwrite values defined in c2 and c1.
This is a very fundamental behavior, and I don't get what is the motivation to change it.

**Comment by odelalleau** [comment]
> The expectation is that any value defined in c3 will overwrite values defined in c2 and c1.
> This is a very fundamental behavior, and I don't get what is the motivation to change it.

I think there's some confusion here because of the example in @Jasha10's first post in this issue, which differs from what he's actually advocating for in his second post here: https://github.com/omry/omegaconf/issues/724#issuecomment-845338809

I believe we all agree with the "priority" order of merge. The main point of discussion (from my PoV) is whether we want to allow
```python
OmegaConf.merge(SubConf, Conf)
```
where `SubConf` is a subclass of `Conf`.

**Comment by omry** [comment]
I don't think that merge is making sense because merge is promoting the object type to enable subsequent type safety.

```python
from dataclasses import dataclass
from omegaconf import OmegaConf


@dataclass
class Animal:
    name: str
    legs: int


@dataclass
class Dog(Animal):
    name: str = "dog"
    legs: int = 4


@dataclass
class Octopus(Animal):
    name: str = "Octopus"
    legs: int = 8
    beak: bool = True


@dataclass
class Config:
    animal: Animal


ret = OmegaConf.merge(Config, {"animal": Dog})
print(OmegaConf.get_type(ret, "animal"))  # <class '__main__.Dog'>
# ref type is not changed by merge, this means we can assign other subclasses of Animal
print(ret._get_node("animal")._metadata.ref_type)  # <class '__main__.Animal'>
ret.animal = Octopus()
print(OmegaConf.get_type(ret, "animal"))  # <class '__main__.Octopus'>

```

**Comment by odelalleau** [comment]
Thanks @omry, I think this example makes it clearer why `merge` currently behaves the way it does. In particular because it shows a merge on a typed sub-node, while our previous discussions were focused on merging at the root level (which lacks a ref type).

Now, my question would be: based on the config at the end of your example (where `ret.animal` is an `Octopus`), let's say someone takes the config `ret` as input and only knows that `ret` is a `Config`, and thus that `ret.animal` is some kind of `Anmial` (without knowing which one). They want to override the current `name` and `legs` values from `ret.animal` by using new values from another `Animal` instance. Currently the following won't work:
```python
animal = Animal(name="legs_got_cut", legs=0)
OmegaConf.merge(ret, {"animal": animal})  # this crashes because `Animal` is not a subclass of `Octopus`
```

It looks like the way to do it is by making the merged config unstructured (btw this probably provides a workaround for my problem in #721):
```python
animal = OmegaConf.structured(Animal(name="legs_got_cut", legs=0))
OmegaConf.merge(ret, {"animal": OmegaConf.to_container(animal)})  # this works
```

However I feel like the prvious `OmegaConf.merge(ret, {"animal": animal})` should also be allowed, at least when `type(animal)` is a super-class of `type(ret.animal)`, because we can expect no new field to be defined.
If `type(animal)` was a different subclass of `Animal` (e.g., a `Dog`) then I agree it's safer to forbid it.

**Comment by omry** [comment]
One thing that you can do now is to merge a dictionary instead of a Structured Config:
```python
@dataclass
class Dog:
    name: str = "dog"
    legs: int = 4

@dataclass
class Octopus:
    name: str = "Octopus"
    legs: int = 8
    beak: bool = True

oct_dict = OmegaConf.to_container(OmegaConf.structured(Octopus))
dog = OmegaConf.structured(Dog)
with open_dict(dog):
    ret = OmegaConf.merge(dog, oct_dict)
    print(ret)
```

I am not sure there is a strong enough case to support the merge you are proposing given that you can merge a plain dict/DictConfig that is not backed by a strict type to achieve the goal.

**Comment by odelalleau** [comment]
> One thing that you can do now is to merge a dictionary instead of a Structured Config:

Yeah that's what I had just realized in my last example (which you pushed further with `open_dict()`). I think it's enough to unblock me so I should be fine. It probably removes a bit of type safety but I don't care much in my own use case.

**Comment by omry** [comment]
Closing, we can re-consider this if there is additional user confusion around this area.
