### ISSUE TITLE
env resolver with ??? default not considered as MISSING

### ISSUE THREAD

**Issue by Ohad31415** [omry/omegaconf#759]
**Describe the bug:**
As far as I remember this used to work fine (At least from omegaconf2.1.0rc), however - 
```python
>>> cfg = OmegaConf.create("db: {user: '${oc.env:DB_USER, ???}'")
>>> assert cfg.db.user == '???'
>>> assert not OmegaConf.is_missing(cfg.db, 'user') 
```
This doesn't give the desired result of the field be missing not treated as a string.
@Jasha10 In our conversion here https://github.com/omry/omegaconf/discussions/729 the behavior seems to be ok. 

**To Reproduce:**
The short lines above. 

**Expected behavior:**
Should be MISSING.

**Additional context:**
- OmegaConf version: 2.1.0
- Python version: 3.9

**Comment by Jasha10** [comment]
`OmegaConf.is_missing` returns `False` for interpolations (because interpolation-to-missing is not the same as a missing value). For example:
```python
cfg2 = OmegaConf.create({"missing": "???", "interp": "${missing}"})
assert OmegaConf.is_missing(cfg2, "missing")
assert not OmegaConf.is_missing(cfg2, "interp")
```
Since `"${oc.env:DB_USER, ???}" is an interpolation, it will also be considered `False` by `OmegaConf.is_missing`.

Would calling `OmegaConf.resolve` be possible in your use-case? Something like this:
```python
>>> cfg = OmegaConf.create({"user": "${oc.env:DB_USER, ???}"})
>>> print(cfg)
{'user': '${oc.env:DB_USER, ???}'}
>>> assert not OmegaConf.is_missing(cfg, "user")
>>> OmegaConf.resolve(cfg)
>>> print(cfg)
{'user': '???'}
>>> assert OmegaConf.is_missing(cfg, "user")
```

**Comment by Ohad31415** [comment]
@Jasha10 Yeah calling `resolve` settles this down thanks.
