### ISSUE TITLE
Incorrect values when using dataclass type object in DictConfig

### ISSUE THREAD

**Issue by ppwwyyxx** [omry/omegaconf#784]
**Describe the bug**
With allow_objects=True I'm unable to use dataclass types as values, however other types work fine.

**To Reproduce**
```
from omegaconf import DictConfig
from dataclasses import dataclass

@dataclass
class A:
    a: int

class B:
    b: int

x = DictConfig(content={"x": 1, "a": A, "b": B}, flags={"allow_objects": True})
print(x)
# {'x': 1, 'a': {'a': '???'}, 'b': <class '__main__.B'>}
```

The value of "a" is incorrect. It seems omegaconf incorrectly treats the dataclass type as a dataclass instance.

**Additional context**
- [x ] OmegaConf version: 2.1.0
- [ x] Python version: 3.9
- [x ] Operating system: linux
- [ x] Please provide a minimal repro

**Comment by ppwwyyxx** [comment]
Python's official doc stated in https://docs.python.org/3/library/dataclasses.html#dataclasses.is_dataclass that to check for dataclass instances, an additional check is needed:

**Comment by ppwwyyxx** [comment]
Here the issue is about using dataclass types, not dataclasses instances.

Could you provide one valid use case where a dataclass type, like what's in the above example, should be automatically converted to a dictionary?

**Comment by Jasha10** [comment]
@ppwwyyxx passing a dataclass type to OmegaConf has a similar effect to passing a dataclass instance.
Here is an example that highlights some use-cases for passing a type instead of an instance:
```python
from dataclasses import dataclass
from omegaconf import OmegaConf, DictConfig

@dataclass
class MyType:
    x: int
    y: int = 123
    def __post_init__(self):
        print("INTSTANTIATED")

cfg = OmegaConf.structured(MyType)
assert type(cfg) == DictConfig
print(cfg)  # prints "{'x': '???', 'y': 123}"
```

Notes:
  - the value for the field `x` was automatically set to `'???'` (it is a `MISSING` value). If passing an instance (instead of a type), `x` would need to be explicitly set.
  - the string `"INSTANTIATED"` was *not* printed. This means that the `__post_init__` method was not run. This is useful for avoiding side-effects of the post-init method.

If you want to later create an actual instance of `MyType` and run the `__post_init__` method, you can do so as follows:
```python
cfg.x = 456
obj = OmegaConf.to_object(cfg)  # prints "INTSTANTIATED"
assert type(obj) == MyType
print(obj)  # prints "MyType(x=456, y=123)"
```

The `"allow_objects"` flag is not documented.
In general, the first-class types supported by omegaconf are:
- dict / DictConfig
- list / ListConfig
- schemas via Structured Configs
- primitive types (`str`, `int`, `Enum`, `float`, `bool`)
Support for other types such as tuples may be implemented in the future. Support for arbitrary objects is not planned.

**Comment by ppwwyyxx** [comment]
OK, thanks for the explanation! I didn't know that dataclass type working like this is expected behavior. I'm closing this then.

**Comment by omry** [comment]
One of the major use cases for using dataclasses with OmegaConf is to do schema validation.
You can do something like:
```python
@dataclass
class User:
  name: str
  age: int

schema = OmegaConf.create({"user": User})
cfg = OmegaConf.merge(schema, {"user", {"name": "bond", "age": 7})
```

The resulting schema will have the name and age fields missing, and the resulting config is a merge of the dict that is validated against the schema config.
