### ISSUE TITLE
StructuredConfig from recursive dataclass

### ISSUE THREAD

**Issue by jmbuhr** [omry/omegaconf#843]
Currently, a structured configuration can be constructed by composing and nesting dataclasses containing simple types. This would  become a lot more powerful and expressive if it where possible to use recursive dataclasses in conjunction with type unions, the latter seems to have been discussed here: https://github.com/omry/omegaconf/pull/381 at some point.

Say for example we want to implement a task list where a task can be either a single task (here represented as a string with an optional multiplicity of how often to perform the task) or a group of tasks (represented as a list of tasks):

```python
@dataclass
class TaskConfig():
    tasks: (str | list[TaskConfig])
    mult: int = 1
```

if we could read the structured config above and merge it with the yaml config below:

```yaml
- do laundry
- mult: 3
  tasks: [feed cat, feed dog]
```

it would lead to a very elegant internal representation. In this case we want to do the laundry once (because the default value of `mult` is 1) and feed the cat and the dog 3 times.

**Describe alternatives you've considered**
A simpler but less elegant solution would be to add arbitrary dictionaries to the types allowed inside of a structured config and parse them elsewhere in the program.

**Comment by Jasha10** [comment]
Hi @jmburh, thanks for outlining this idea :)

One thing that has been on my mind is the question of how to handle ambiguity, where a value assigned to a union-typed structured config field could be interpreted as one of several types that are present in the union type hint. For example:
```python
from omegaconf import OmegaConf, MISSING

@dataclass
class Schema():
    task_or_dict: TaskConfig | Dict[str, Any] = MISSING

cfg = OmegaConf.create(Schema)
cfg.task_or_dict = {"tasks": "foo"}
```
The question is, in the last line above, should the assigned value be treated as a `TaskConfig` or as a `Dict[str, Any]`?

So far I can think of two ways to resolve such ambiguity:
1. type the value as belonging to the leftmost compatible argument appearing in the union. In the example above, the assignment of `{"tasks": "foo"}` would be typed as `TaskConfig` (not `Dict[str, Any]`) because `TaskConfig` appears further to the left in the type hint `TaskConfig | Dict[str, Any]`. This would let users decide how to handle ambiguity by ordering the arguments to their union type hint.
2. Create special rules that "do the right thing", e.g. giving precedence to structured configs when possible. In the example above, `{"tasks": "foo"}` would be typed as `TaskConfig` because `TaskConfig` is a structured config.

I am leaning towards option 1 above because I think it would be relatively easier to implement, and not overly complicated for users to reason about.

**Comment by Jasha10** [comment]
I am going to close this in favor of #144, which should cover the same surface area.
