### ISSUE TITLE
Have `bytes` as supported value type.

### ISSUE THREAD

**Issue by pedropgusmao** [omry/omegaconf#844]
**Is your feature request related to a problem? Please describe.**
I need to instantiate an object with another one which is basically a dataclass instance like:
```@dataclass
class Parameters:
    """Model parameters."""
    tensors: List[bytes] 
    tensor_type: str 
```
when trying to use this I get:
`omegaconf.errors.ValidationError: Unsupported value type: <class 'bytes'>`
Example:
```from dataclasses import dataclass
from typing import List

from omegaconf import OmegaConf

@dataclass
class Parameters:
    """Model parameters."""
    tensors: List[bytes] 
    tensor_type: str 

# omegaconf.errors.ValidationError: Unsupported value type: <class 'bytes'>
OmegaConf.structured(Parameters)
```

**Describe the solution you'd like**
Accepting `bytes`.

**Describe alternatives you've considered**
Internally interpreting `bytes` as `str` (when parsing) then converting it to `bytes`.

**Additional context**
...

**Comment by Jasha10** [comment]
Thanks for suggesting this @pedropgusmao.
Supporting `bytes` seems reasonable to me since `bytes` is a built-in type and since yaml supports the `bytes` type natively.

**Comment by pixelb** [comment]
Thanks for the suggestion and implementation!

I agree this has some merit, as binary is a yaml primitive: https://yaml.org/type/binary.html
Playing devil's advocate, some thoughts against implementing this:

- "binary" is just a base64 string, so why not do a little manual conversion in code to/from storing b64 in existing strings?
  - It would be good to have a concrete example of before/after code for this use case. BTW I vaguely remember a suggestion to support tensor as a primitive type, which had less merit, but some of the same considerations as this, as that's what's presented as the use case. Also slightly related to leaning on explicit conversion more is issue #805 discussing numpy float handling.
- We have to be careful to avoid becoming a data serialization mechanism. We're tuned for smaller amounts of config, rather than larger amounts of data

If we do support bytes, I'm not sure about the support for converting to/from strings. That would have to be restricted to utf-8, so I don't see the use case for this conversion support

**Comment by Jasha10** [comment]
I've agree about the conversion support -- it's cleaner in my opinion if assigning `str` to a `bytes` field fails and assigning `bytes` to a `str` field fails.
cc @jieru-hu

**Comment by Jasha10** [comment]
>     * "binary" is just a base64 string, so why not do a little manual conversion in code to/from storing b64 in existing strings?
>       
>       * It would be good to have a concrete example of before/after code for this use case. 

@pedropgusmao, would you mind giving a motivating example?

**Comment by pedropgusmao** [comment]
Hello @Jasha10 and @pixelb , 
Thank you both for the comments.

Tbh, my use case is not really related to conversion the `str` <-> `bytes` , nor is it directly related to loading `bytes` from `.yaml` files. 
Instead, I'm looking for simple/clean way to set all my regular parameters  (`str`, `float`, etc...) and to instantiate different implementations of an given interface inside a single `.yaml` config file.

As you must definitely know, both things can be achieved using [Hydra](https://hydra.cc/docs/advanced/instantiate_objects/overview/), where calling `hydra.utils.instantiate(cfg.obj,named_arg=parameters)` would solve for the instantiation part of the problem. However, even if `parameters` is created inside my python script (i.e. not inside the '.yaml' file), I get the error seen at the beginning of this [Issue](https://github.com/omry/omegaconf/issues/844#issue-1084971111). Allowing `bytes` to be supported in OmegaConf would allow `Hydra` to accept `bytes`-containing data classes as input to its `hydra.utils.instantiate`.
